language: python
python:
  - 2.7
before_install:
  - echo "Robotice build started"
env:
  global:
  - ROBOTICE_TEST=True
  - R_ROOT_DIR=:/home/travis/build/robotice/robotice
  - PYTHONPATH=:/home/travis/build/robotice/robotice
  - R_WORKER_DIR=/home/travis/build/robotice/robotice/robotice/test/conf
  - R_CONFIG_DIR=/home/travis/build/robotice/robotice/robotice/test/conf
  - R_GRAINS_DIR=/home/travis/build/robotice/robotice/robotice/test/conf
install:
  - "pip install -r requirements/testing.txt"
script: 
  - python setup.py nosetests -w robotice/test/tests/utils/
  - python setup.py nosetests -w robotice/test/tests/monitor/
  - python setup.py nosetests -w robotice/test/tests/reactor/
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
    - 6du1ro.n@gmail.com
    on_success: never
    on_failure: always