language: python
python:
  - 2.7
  - 2.6
before_install:
  - su robotice export ROBOTICE_TEST=True 
install:
  - "pip install -r requirements/testing.txt"
script: nosetests
after_success:
  - coveralls
branches:
  only:
    - master
notifications:
  email:
    recipients:
    - 6du1ro.n@gmail.com
    on_success: never
    on_failure: always