language: python
python:
  - 2.7
before_install:
  - export ROBOTICE_TEST=True 
install:
  - "pip install -r requirements/testing.txt"
script: nosetests
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
    - 6du1ro.n@gmail.com
    on_success: never
    on_failure: always