language: python
python:
  - 2.7
before_install:
  - export ROBOTICE_TEST=True
  - export R_WORKER_DIR=/home/travis/build/robotice/robotice/robotice/test/conf
  - export R_CONFIG_DIR=/home/travis/build/robotice/robotice/robotice/test/conf
  - export R_GRAINS_DIR=/home/travis/build/robotice/robotice/robotice/test/conf
install:
  - "pip install -r requirements/testing.txt"
script: 
  - nosetests /home/travis/build/robotice/robotice/robotice/test/tests/utils
  - nosetests /home/travis/build/robotice/robotice/robotice/test/tests/reactor
  - nosetests /home/travis/build/robotice/robotice/robotice/test/tests/monitor
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
    - 6du1ro.n@gmail.com
    on_success: never
    on_failure: always